### ISSUE TITLE
Integrate "plugin.video.abelhas" with Kodi/XBMC Library

### ISSUE THREAD

**Issue by jorgeavlobo** [fightnight/fightnight-addons#47] opened 2015-04-30 11:54 UTC
I hereby submit a special request that would escalate the quality of the already awesome and unique add-on!

- Is it possible to make the "Abelhas Add-on" integrated with the Kodi/XBMC Library?

This way we would be able to use other add-ons like movie scrapers to gather all the info about the movies, I am thinking about the "Fanart Downloader" for example. It has already been done with Genesis:
https://seo-michael.co.uk/how-to-integrate-genesis-with-xbmc-library/
or
http://kinkeadtech.com/2015/03/how-to-merge-kodi-streaming-add-ons-into-the-video-library/

We would get all our files way more organized and user friendly presented on the Kodi/XBMC home screen with all their information from severeal websites.

Another way of doing this would be to add the feature of a movie scraper to the Abelhas Add-on itself, but I guess that it would be way more demanding and time consuming for an add-on that is already great!

Thanks in advance and keep up the awesome work!

**Comment by gb160** [comment] 2015-05-18 12:53
I hereby second this request !!
Its already a superb addon, if it had the Library integration that Genesis offers it would be head and shoulders above all else.Id love to see this feature.

**Comment by Mafarricos** [comment] 2015-05-18 14:44
No promises, but probably something can be arranged, in the near future (without any ETA) I will make a PR to see if fightnight likes the way I think Library integration can be achieved (at least to movies).

**Comment by gb160** [comment] 2015-05-18 21:16
excellent news, i'll keep an eye open for progress

**Comment by Mafarricos** [comment] 2015-06-04 21:55
Already made a PR to get this going on ;)

**Comment by gb160** [comment] 2015-06-05 08:28
great to see progress on this so soon !

Im testing it out right now and theres something i noticed...

when i add a tv episode to the library, its using the path:
userdata/addon_data/plugin.video.abelhas/Movies/
to store the episodes.

is it possible to somehow have a separate folder for movies and tv ?
im not sure how to add the folder as a kodi video source with both movies and tv episodes in the same location....unless I'm being stupid and missing something obvious?...i may well be missing something important as some of my menu options aren't showing in English...but some are.

Regardless many many thanks for working on this.

**Comment by Mafarricos** [comment] 2015-06-05 08:40
I only had in mind movies.
I will make change context menu, so you can have the option: Add to library (Movies), Add to library (TVShows) and the user have to choose.
That's a simple change.
Even so, for tvshows as you add episode by episode, probably some changes have to be made, so the episodes go all to the same folder, this will need more work.

**Comment by gb160** [comment] 2015-06-05 09:02
That would be excellent if possible...
Ive only tested a couple of movies so far but its working very well.

**Comment by Mafarricos** [comment] 2015-06-05 21:17
Already created one folder to movies and another to tvshows.
Now via context menu the user have to choose the type of content to be added to library.

But tvshows still need improvement because of season and episode number.

**Comment by gb160** [comment] 2015-06-06 10:58
This is brilliant , its working very well for me apart from one issue I've noticed...
an example:
if i search for the TV show Aquarius...the results work as expected.
if i search for Aquarius 1080p....the results have ,i think,some html tags at the end of them(</a></p>)
when the results have these tags,i can play the files as normal, but if i try to add these to library i get a script error message and they don't get added.
I can send u a log if u need it, but its seems pretty easy to reproduce.

Well done anyway...its excellent work !

**Comment by gb160** [comment] 2015-06-06 11:09
Should've mentioned I've tested this with the current version of the addon and the html tags are missing from both searches.

**Comment by Mafarricos** [comment] 2015-06-06 14:56
Is good to have another people testing the changes.
Already changed the regex to find the name.

My release plugin.video.abelhas-1.0.2e already have that corrected.
https://github.com/Mafarricos/Mafarricos-xbmc-dev-addons/commit/61e8ebfb6003a6dddee624a5da1c6cccc75fe8f3
If you have my dev-repo you should get the update.

**Comment by gb160** [comment] 2015-06-06 15:41
Ive just added your repo and its now working perfectly.
Again, many thanks for this excellent feature !!

**Comment by Mafarricos** [comment] 2015-06-06 21:55
Tweaked a bit.
https://github.com/Mafarricos/Mafarricos-xbmc-dev-addons/commit/d49fbc41963222d15f24bc510f6e6efcce331956

Batch addition ;)

Will only work with files of folder you are browsing.
For tvshows with format ShowNameSXXEXX or ShowNameSXX-EXX probably will add everything without asking nothing.
About the movies will always ask for name of folder to be created.

**Comment by gb160** [comment] 2015-06-07 09:16
now this is really starting to get good !
Last night i went thru the process of manually adding a tv series, it took AGES , but it worked....this morning I've added an entire series in about a minute thanks to this 'batch' feature...superb work my friend.

The only advantages that genesis has over this now are cosmetic...eg the tv show poster showing on the osd when an episode is played.

I have one question that i hope u can answer, forgive me for going off topic....ever since I've been using the Abelhas addon, about 50% of the time, when i select a show or movie to watch, i get the error "Albehas Not Available. Retry later"...i select it again and it plays very time....do u know if this can be fixed? 
Its not a huge problem as they ALWAYS work on the second attempt....its quite similar to an issue i had with playing video from a samba share....i adjusted a timeout in my advanced settings.xml which solved this problem, is there any such fix for the "not available.Retry Later" error ?

Excellent progress !!

**Comment by Mafarricos** [comment] 2015-06-07 12:46
I never had the error "Albehas Not Available. Retry later" but usually that's a problem in the server side, not the addon.
Only with logfile can be confirmed.

**Comment by gb160** [comment] 2015-06-07 17:21
I seem to have found a slight problem mate...
in the addon settings,ive set my tv and movie folders to be on a smb share with all my other media.....but when i try to add a show, batch or not, the .strm files don't get created...i definitely have write permissions, as the show folder, and the series folder are created on the smb share, but the strm files are not. 
If i set the folders back to the default location they get added correctly
 
I've got a log if this helps...
http://xbmclogs.com/pcvj3ewgn

Regards

**Comment by Mafarricos** [comment] 2015-06-07 18:56
I will check it, probably the method to write the file has to be changed to the method used to create the folders.

**Comment by Mafarricos** [comment] 2015-06-07 21:32
@gb160 check if latest release fixes your problem saving. 1.0.2g

**Comment by gb160** [comment] 2015-06-07 21:48
Hi Ive just tried it and its still the same...the series folder is created but remains empty.
log is here.
http://xbmclogs.com/pwe7ltwug

**Comment by Mafarricos** [comment] 2015-06-07 21:56
Can you check if genesis addon saves in samba share?
I never used one to save my files, so I don't know if is a limitation, but probably code missing.

**Comment by Mafarricos** [comment] 2015-06-07 22:02
Released 1.0.2h, with the same code as genesis to save strm files.
I had some differences. Check if that way works.

**Comment by gb160** [comment] 2015-06-07 22:06
Just checked and Genesis definitely saves the .strm to the samba share, hope this fixes it.... 
I'm only seeing 1.0.2g right now?

**Comment by Mafarricos** [comment] 2015-06-07 22:09
1.0.2h already on github ;)

**Comment by gb160** [comment] 2015-06-07 22:10
1.0.2h tested and working fine !
Good Work ...sorry for being a pest lol

**Comment by Mafarricos** [comment] 2015-06-07 22:12
Cool, this way when fightnight integrates my code many things are perfectly tested ;)

**Comment by gb160** [comment] 2015-06-08 08:32
Ive found a little bug mate ....
I don't think the watched state is getting updated when i watch an entire episode...ive tried this on two diff series so far, the episodes aren't getting marked as watched...im sure genesis implements this.
also if i watch half an episode , and go back to it later, I'm not asked if i want to resume...it just starts from the beginning again....i guess this is the same problem.

**Comment by Mafarricos** [comment] 2015-06-08 08:36
I didn't implementing nothing about watched. For that you need Trakt addon. As in abelhas I can't identify the real movie or tvshow. Only the things added to library can be identified by trakt.

Genesis also identifies internally, so in addon they can be marked. But abelhas isn't a movies/series site.

About the resume, is also a functionality that never existed in abelhas.

So those aren't bugs, but improvements or new features ;)

**Comment by gb160** [comment] 2015-06-08 08:42
Ahhh ok...that makes sense...sorry for pestering again.....although if you find time they would be excellent features to add ;)

**Comment by jorgeavlobo** [comment] 2015-06-08 09:29
Only now I am testing it! Whow, my movie collection seems nice and tidy!!!
Can you add on nice feature please?
After you "Add to Library" in Abelhas, can you implement for Kodi to update the Library?
AKA, do the following steps:
Kodi > Videos > Files > Right Click on Movies/TV Series Folder > Scan for new content

That way we only need to setup the Movies Master Folder in Kodi and add one file at a time in Abelhas.

**Comment by jorgeavlobo** [comment] 2015-06-08 09:34
I second on the resume feature! ;)
It is awesome!

**Comment by jorgeavlobo** [comment] 2015-06-08 09:42
In Abelhas, if the file is already added to the Library, do you think it might be useful to have a Remove from Library feature?
Maybe common users won't be able remove the old folder manually if they want it.

**Comment by gb160** [comment] 2015-06-08 10:15
@jorgeavlobo @Mafarricos 
I see the code is already there to auto update the library, however it wasn't working for me either.
i checked the code used in genesis and its slightly different.

I fixed it by using the genesis code which is as follows...

xbmc.executebuiltin('UpdateLibrary(video)')

in genesis the same code is used for both TV and Movies....so the "if type== Tvshow"  or "if type==movie" condition isn't needed.
i changed the code in both the add_to_library_batch function, and the add_to_library function
Its working as expected now.

I thought id chip so that  @Mafarricos can concentrate on the 'new features' we keep demanding !!

**Comment by jorgeavlobo** [comment] 2015-06-08 11:04
In Abelhas, when you > right click on a movie > Add to Library (Movie/TV Series) and now if you have a second thought and decide to cancel the "Create Folder" window, by either hitting the "X" or pressing ESC on the keyboard, you will get a Script Failed! message.

**Comment by jorgeavlobo** [comment] 2015-06-08 11:05
In Abelhas, when you > right click on a movie > Add to Library (Movie/TV Series) and now if you have a second thought and decide to cancel the "Create Folder" window, by either hitting the "X" or pressing ESC on the keyboard, you will get a Script Failed! message.

**Comment by jorgeavlobo** [comment] 2015-06-08 11:21
In Abelhas, Add to Library (TVShow) - Batch, it won't work if the series is called:
Castle s01e01
Castle s01e02
Castle S01e03
etc, etc...
I guess it is because of the space, I dunno.
Can the plugin accomodate this detail in TV Series naming?
Thanks

**Comment by jorgeavlobo** [comment] 2015-06-08 12:01
In order to have the best experience with this Library Integration feature, set the following default views in your Kodi (with default Confluence skin):
- Click "Movies" on the main screen > drag mouse to the left of the screen > select view: Fanart
(Make sure you have "Universal Movie Scraper" set for Movies).

- Click "TV Shows" on the main screen > drag mouse to the left of the screen > select view: Fanart > now enter one of your TV Series (that has several seasons) by clicking on it > drag mouse left side of screen View: Poster Wrap > now enter one of the seasons by clicking on it > drag mouse left side of screen View: Media Info.
(Make sure you have "The TVDB" scraper set for TV Shows).

With Kodi setup properly and Abelhas Add-on installed, it can now provide and awesome user friendly experience!!!

Great job @Mafarricos !!!

**Comment by jorgeavlobo** [comment] 2015-06-08 12:40
Definições do Abelhas > Configurações Gerais > Movie Library Integration Folder
Can we have more saving paths options?
I wanted to add an FTP server so that I save my *.strm files there.

It is possible in Kodi to add files to the library from FTP servers for example:
Kodi Main Screen > Videos > Files > Add Videos... > Browse > Add network location... > Protocol: FTP Server

Since I have several devices with Kodi installed (Android, Windows and OSX) it would simplify the configuration of each device!

Thanks!

**Comment by jorgeavlobo** [comment] 2015-06-08 19:49
Abelhas already has implemented the features:
Add to Library (Movies)
Add to Library (TV Shows)

Would it be asking too much for the feature:
Add to Library (Animations)

The kids over here would love to see this working!!!

Cheers!!

**Comment by jorgeavlobo** [comment] 2015-06-08 20:48
I just tested in Abelhas:
Add to Library (Movie) - Batch

I thought it was intended for movies divided in two files or something, for example:
batman.cd1.avi
batman.cd2.avi

Aparently I was able to add to library a group of movies on that same folder (not subfolders):
batman.avi
spiderman.avi
godzilla.avi

I got a script error but it still worked.
Dunno if it was intended this way.

Any insights on "Add to Library (Movie) - Batch"?

Many thanks!

**Comment by Mafarricos** [comment] 2015-06-08 22:05
@jorgeavlobo 
The Movie batch is to add like that:
"Aparently I was able to add to library a group of movies on that same folder (not subfolders):
batman.avi
spiderman.avi
godzilla.avi"

I will need a logfile to understand the error. Right now with my usage I didn't got any error.

**Comment by Mafarricos** [comment] 2015-06-08 22:07
@jorgeavlobo and @gb160 please open new issues here:
https://github.com/Mafarricos/Mafarricos-xbmc-dev-addons/issues
It's easier to track and close solved problems or requests.

**Comment by jorgeavlobo** [comment] 2015-06-08 22:39
Done, each different subject with different topics.

Excelente trabalho!!!

**Comment by Mafarricos** [comment] 2015-06-08 22:59
Add to library with autoupdate, the series name bug and X close the add to library should be fixed ;)

**Comment by Mafarricos** [comment] 2015-06-08 23:03
@jorgeavlobo all topics already have a response.

**Comment by jorgeavlobo** [comment] 2015-06-08 23:16
Poxa, já reparei... Isso é que é trabalhar...
Para quando a versão oficial?

**Comment by Mafarricos** [comment] 2015-06-08 23:18
Isso já é com o @fightnight.

**Closed** 2015-06-11 15:27 UTC
